### ISSUE TITLE
Rework the way collections are constructed

### ISSUE THREAD

**Issue by cmcknight** [cmcknight/central-supply-catalog#67]
The current approach to collections has some being built from a single top-level file and others being built from a collection of files in a directory. This poses an issue for generating departments/subdepartments that have no entries. Specifically empty product arrays generate no pages.

The proposed solution is to build individual collections for each type and do away with the top-level collection. The benefits of doing so will consolidate the way collection pages are generated. The top-level 'department' pages should be titles on the dropdown but have no backing url.

**Comment by bobbyjim** [comment]
Totally agree.  This is how the application accesses the catalog anyway, so there's a conceptual match.
